### ISSUE TITLE
Window closes after clicking Open Spread Sheet

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#11]
After running for 9 hours and forgetting to take a screenshot, I clicked on Open Spread Sheet button and the results window disappered. I think it should stay open in the background until I clicked on close.

**Comment by earlephilhower** [comment]
Thanks.  While I appreciate the feedback, I'm going to have to chalk this up as a personal preference.

As more detailed data is present in the spreadsheet that's opened, I'd say it's OK to close the window.

Closing.
