### ISSUE TITLE
fio json+ output format now directly provides latency durations and needs no translation 

### ISSUE THREAD

**Issue by vincentkfu** [earlephilhower/ezfio#16]
@earlephilhower, I saw your latest exceedance chart commit and realized that I did a poor job of advertising changes in fio's json+ output format.

http://git.kernel.dk/cgit/fio/commit/?id=129e4193ba3f6e840990fdd5f09c9742bb0dddfa actually changed the json+ output format to drop the indices for the raw clat data structure in favor of the actual latency durations

the recent nsec timing patches only changed the units from usec to nsec

**Comment by earlephilhower** [comment]
Howdy Vincent,

No problem, it was pretty evident what you were doing right from the (much nicer) JSON+ output.  I've run against the 2.99 tag and believe it's all good now (and should fall back for older FIO releases to your PLAT_* stuff).  The ODS graphs are still shown in us, so I just divide the JSON ns values by 1000 to give floating point values in us.

I've done a few runs internally and it all seems good, but if you see something I've done that's wrong, I'm happy to fix it.

Thx again,.
-EFP3

**Comment by vincentkfu** [comment]
Ah, ok I see. I didn't look closely enough at your changes but now see that you do the right thing with 2.99.
