### ISSUE TITLE
Block size less than 4096 not working on PCI NVMe Adapters

### ISSUE THREAD

**Issue by narasimhan-v** [earlephilhower/ezfio#2]
Hi Earle,

I tried ezFIO on PCI NVMe adapters, which are formatted with 4k sector.
So, fio reports error on these devices for `bs` less than 4096.

Is this something that should be changed in the bs values in the ezfio script ?

**Comment by earlephilhower** [comment]
Howdy,

Good point, and not something I thought of before.  There's a new commit with a check for the minimum IO size before each test.  It'll skip the 512b, 1k, and 2k tests on devices with 4K physical/logical sectors (returning "0" for all test values on these runs).  

-EFP3

**Comment by narasimhan-v** [comment]
@earlephilhower Thanks for the fix :)
Though, I had skipped tests by checking with `blockdev --getpbsz`.
Also, I skipped appending the test to `oc`

**Comment by earlephilhower** [comment]
It'll skip the test, but the problem is the graphs are coded in the sheet to expect a certain # of runs.  So you'll be OK on the text output, but if you look at the graphs in the ODF file it'll be completely out of whack.

**Comment by narasimhan-v** [comment]
Closing as the issue is fixed.
