### ISSUE TITLE
Intel 760 Test for Review

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#21]
Earle Hi,

we have performed a test on Intel 760P 512 GB M.2 SSD. You can check the results if everything is OK.

Thanks.

[details_512GB_12cores_3696MHz_PHYSICALDRIVE1_DESKTOP-FC2A4TG_2018-04-05_14-42-15.zip](https://github.com/earlephilhower/ezfio/files/1914724/details_512GB_12cores_3696MHz_PHYSICALDRIVE1_DESKTOP-FC2A4TG_2018-04-05_14-42-15.zip)

**Comment by earlephilhower** [comment]
Howdy,

With the disclaimer that I work for a competitor and can't comment on the product under test, the reported test results didn't seem to have anything that stood out to me as anomolous.  Looks like a clean run!

Thx
-EFP3
