### ISSUE TITLE
970 PRO Results

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#23]
Just wanted to share my 6:45 hours of 970 PRO tests. Anything wrong?

[ezfio-master.zip](https://github.com/earlephilhower/ezfio/files/1957560/ezfio-master.zip)

**Comment by earlephilhower** [comment]
Looks nice.  The 4K Random Write looks bad as presented, but isn't really.  Just set the y axis lower limit to 0 and it'll looks nice and flat at ~34K.

**Comment by earlephilhower** [comment]
And the QD 256 dip may be simply CPU limitations.  You normally want to have a 2-socket or a high core count 1-socket Xeon at those depths.
