### ISSUE TITLE
Missing timeseries data and graph in .ODS file

### ISSUE THREAD

**Issue by Crash-Edwards** [earlephilhower/ezfio#29]
Hi,

We are having an issue where the .ods file is missing the Long Term Performance Stability Graph and the Timeseries tab has the computer information but is missing all the IOPS numbers. Everything else is working. 

We are Running the test on Windows Server 2016 with PowerShell 5.1 and FIO 3.12.   
Any help would be appreciated.

**Comment by earlephilhower** [comment]
Howdy,

You'll need to look at the logs that are generated in the details/ subdirectory.  Most likely FIO is not running for some reason on that specific test or the logger is not able to grab IOPS from the Windows subsystem (weird perfmon permissions or something?).

If the data is all public, you can attach a ZIP here and I can look if there's something obvious.  But if it's proprietary or confidential, of course, please don't as anyone can see these messages.

Thx
-EFP3

**Comment by Crash-Edwards** [comment]
EFP3, 
Actually the files TestRand_w30_bs4096_threads256_iodepth1_PhysicalDrive5.out, TestRand_w30_bs4096_threads256_iodepth1_PhysicalDrive5.out.exc.read.csv and TestRand_w30_bs4096_threads256_iodepth1_PhysicalDrive5.out.exc.write.csv all exist in the directory and have data in them. 

However the ezfio_timeseries_960GB_8cores_3193MHZ_PhysicalDrive5_servername_date.csv has no IOPS data in it.


Thanks
Crash

**Comment by earlephilhower** [comment]
There should be a .log file there as well (although w/Windows I think that sometimes some errors may end up in the powershell console).  W/o that or a full zip I can't really point you to anything, sorry.

**Comment by Crash-Edwards** [comment]
Are you talking about the iostat_ezfio_date_time file?

**Comment by earlephilhower** [comment]
iostat file plus the .out associated with it.  They are meant to capture the raw FIO output, while the CSVs are just the post-processed versions of FIO output or perfmon monitors.

**Comment by Crash-Edwards** [comment]
You are correct the iostat file is missing and was never created.

**Comment by Crash-Edwards** [comment]
EFP3,
Just to let you know this seems to be a user error (me) where the PerfMon logging and alert service was disabled. After setting it to automatic the issue was resolved. 
 
Thanks for all your help!

**Comment by Crash-Edwards** [comment]
Resolved by setting the PerfMon alert and logging service to automatic.

**Comment by earlephilhower** [comment]
Great, thanks.  If someone else has the same problem we've got one more thing to check, now!
