### ISSUE TITLE
Enabling for ppc64 architecture

### ISSUE THREAD

**Issue by narasimhan-v** [earlephilhower/ezfio#3]
Hi,
I have found out cpuinfo parsing works differently for ppc64 architecture.
I have a patch ready for this. Will be sending a pull request.

Can I send it directly on the master branch ?

**Comment by earlephilhower** [comment]
Sure, send a pull and I'll check it against the amd64 boxes we're running here.  If you have a sample of cpuinfo output from PPC can you reply with it here just so I can see the differences?  Thx.

**Comment by narasimhan-v** [comment]
Have pasted the output of `/proc/cpuinfo` here
```
processor	: 0
cpu		: POWER8 (architected), altivec supported
clock		: 3957.000000MHz
revision	: 2.0 (pvr 004b 0200)

processor	: 1
cpu		: POWER8 (architected), altivec supported
clock		: 3957.000000MHz
revision	: 2.0 (pvr 004b 0200)

processor	: 2
cpu		: POWER8 (architected), altivec supported
clock		: 3957.000000MHz
revision	: 2.0 (pvr 004b 0200)

processor	: 62
cpu		: POWER8 (architected), altivec supported
clock		: 3957.000000MHz
revision	: 2.0 (pvr 004b 0200)

processor	: 63
cpu		: POWER8 (architected), altivec supported
clock		: 3957.000000MHz
revision	: 2.0 (pvr 004b 0200)

timebase	: 512000000
platform	: pSeries
model		: IBM,8286-42A
machine		: CHRP IBM,8286-42A
```

**Comment by narasimhan-v** [comment]
@earlephilhower Do I have permission to submit a pull request ?

**Comment by earlephilhower** [comment]
Sure, please do.  Anyone can send in a pull request, it's just up to the repo owner to merge or not.

**Comment by narasimhan-v** [comment]
```
# git push upstream master 
ERROR: Permission to earlephilhower/ezfio.git denied to narasimhan-v.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
I get this error.
I think you need to add me as a collaborator, according to [link](https://help.github.com/articles/error-permission-to-user-repo-denied-to-other-user/)

**Comment by earlephilhower** [comment]
Please fork the project at github, check that out to your local system, apply the patch, commit and push to your GH fork, then you can do a pull request from the github web UI.  That's the way these are normally handled.

**Comment by narasimhan-v** [comment]
I did that exactly, and got the same error again

**Comment by earlephilhower** [comment]
There are no forks shown for the project, so you've not forked to your own repo yet.  You need to use the fork button in the upper right-hand side from my project URL to fork into your own private version @GH, check *that* version out (git clone http://github.com/narasimhan-v/...), apply your patch, commit, push, then go back to the github website and submit the pull request from your repo's home page.

**Comment by narasimhan-v** [comment]
Sorry, there was some problems with my system.
Created pull request #4
