### ISSUE TITLE
Expression: !trylock Assertion failed! on Windows 10

### ISSUE THREAD

**Issue by hkr1990** [earlephilhower/ezfio#39]
Hi,

I'm running ezFio on windows 10 using fio-3.16 (source : https://bsdio.com/fio/ ). I'm consistently seeing this error related to !trylock. Any suggestion as to how to fix it for Windows ?

*****************************************************************************************************
ezFio test parameters:
Drive               : \\.\PhysicalDrive0
Model               : Samsung SSD 970 EVO Plus 250GB
Serial              : 0025_385C_XXXX_XXXX.
AvailCapacity       : 233 GiB
TestedCapacity      : 35 GiB
CPU                 : Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
Cores               : 8
Frequency           : 3501
FIO Version         : fio-3.16

Test Description                                                          BW(MB/s)      IOPS  Lat(us)
------------------------------------------------------------------------- -------- --------- --------
Sequential Preconditioning                                                   DONE      DONE     DONE
Sequential Preconditioning                                                   DONE      DONE     DONE
---Sustained Multi-Threaded Sequential Read Tests by Block Size---
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=512         44.2     90469   1425.6
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=1024        91.4     93633   1375.7
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=2048       194.8     99752   1290.5
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=4096       377.4     96625   1334.3
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=8192       746.7     95578   1347.5
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=16384     1474.1     94343   1367.8
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=32768     2687.3     85992   2101.4
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=65536     2583.2     41331   6189.9
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=131072    2508.9     20071  12751.6
Program: C:\Program Files\fio\fio.exe
File: filelock.c, Line 182

Expression: !trylock
Assertion failed!

Program: C:\Program Files\fio\fio.exe
File: filelock.c, Line 182

Expression: !trylock
Assertion failed!

Program: C:\Program Files\fio\fio.exe
File: filelock.c, Line 182

Expression: !trylock
Assertion failed!

Program: C:\Program Files\fio\fio.exe
File: filelock.c, Line 182

Expression: !trylock
Assertion failed!

**Comment by hkr1990** [comment]
Installed FIO 3-19.

**Comment by earlephilhower** [comment]
Thanks for the update!  I thought fio 3.1X had a problem under Windows where it no longer could access PhysicalDrives.  Did you have no issues with 3.19?

**Comment by hkr1990** [comment]
It works fine for me on Windows 10. The only pre-requisite is to "Delete the volume under test" using the Disk management application.
