### ISSUE TITLE
__fio_lock_file: Assertion `!trylock' failed.

### ISSUE THREAD

**Issue by qiuxin** [earlephilhower/ezfio#40]
No idea what happen. Are there any tools I miss prior to run the script?

---Sustained Perf Stability Test - 4KB Random 30% Write---                                         
Sustained Perf Stability Test - 4KB Random 30% Write                              00:20:10         
FIO Error!
fio /tmp/tmpgqkch6qd --output-format=json+
STDOUT:

STDERR:
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.

**Comment by qiuxin** [comment]
[/usr/local/robert]# fio -version
fio-3.14

This is the fio version

**Comment by qiuxin** [comment]
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.

Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./ezfio.py", line 1120, in JobWrapper
    val = o['cmdline'](o)
  File "./ezfio.py", line 974, in <lambda>
    o['runtime'])})
  File "./ezfio.py", line 862, in RunTest
    raise FIOError(" ".join(cmdline), code, err, out)
FIOError

Sustained Perf Stability Test - 4KB Random 30% Write                       ERROR     ERROR    ERROR
ERROR DETECTED, ABORTING TEST RUN.

**Comment by earlephilhower** [comment]
Please use a newer FIO.  See https://github.com/axboe/fio/pull/838 . The highly threaded sustained test needs many FIO internal file handles to do its work, but originally there was a very low limit on them in FIO.
