### ISSUE TITLE
The capacity of drive is different from NVMe list

### ISSUE THREAD

**Issue by qiuxin** [earlephilhower/ezfio#41]
The capacity of drive is different from NVMe list. 

I use nvme list , the capacity is 6.4TB.   The capacity of the same drive is  5961G.
Would you please do me favor to let me know the reason?

[root/ezfio-master]# ./ezfio.py -d /dev/nvme2n1 -u 100 --yes
***************************************************************************************************
ezFio test parameters:
               Drive: /dev/nvme2n1
               Model: 
              Serial: 
       AvailCapacity: 5961 GiB
      TestedCapacity: 5961 GiB

**Comment by earlephilhower** [comment]
HDD-vendor "GB" vs computer "GiB".  SSDs are sold as 10^9 == 1GB.  Computers use 2^30 - 1GiB.  Hence, the reporting of G*i*B vs. "GB."  See https://en.wikipedia.org/wiki/Gibibyte

`2^30 * 5,961` = `6,400,575,012,864` bytes
