### ISSUE TITLE
Display the exact test parameter -thread number?

### ISSUE THREAD

**Issue by qiuxin** [earlephilhower/ezfio#42]
I am reading the "ezfio.py" file in the lines between 1013- 1020,  the name and print info is "Multi-thread", but the thread parameter is 1. Is this a typo?
BTW, how about displaying the exact thread number instead of "multi-Threaded"?  I guess most of the testers want to know the test parameter?

   testname = "Sustained Multi-Threaded Sequential Read Tests by Block Size"
    seqrand = "Seq"
    wmix = 0
    threads = 1
    runtime = shorttime
    iops_log = False
    iodepth = 256
    AddTestBSShmoo()

**Comment by earlephilhower** [comment]
No, not a typo.  It's 256QD.

The code is a little sloppy with the word "thread."  It's the total queue depth, rather than threads, when the script says threading.  So here it has 256 I/Os in flight with 1 thread running them.  Other tests do 16 threads, 16 QD per thread = 256 QD.  It's never really been an issue with enterprise users as "thread" and "QD" in this space are commonly used to describe the "outstanding I/Os" anyway.

**Comment by qiuxin** [comment]
Double check： The word "thread" is completely equvenlent to "fio job", correct?

**Comment by earlephilhower** [comment]
It's complicated.  Each test is only one FIO job, but a job can have multiple test threads.  A fio thread can be running sync, or 1 QD (i.e. it uses standard POSIX pread/pwrite).  That would be 1 thread or 1 QD.  But, a FIO job can also be running async IO which lets 1 FIO thread have multiple outstanding IOs.

So for the max read iops/block: https://github.com/earlephilhower/ezfio/blob/79909e6cce3f8dd6d1b0929156014d9c6d396d93/ezfio.py#L1022-L1029

I do 1 FIO job which spawns 16 threads, each with 16 QD as async IO.  For a total of 256.

Hope that clears it up a little bit.  The actual fio.job files are preserved in the `details` directory, so you can examine them offline after a run.

**Comment by qiuxin** [comment]
The is a parameter called "--numjobs=$numjobs" in fio.  As far as my understanding,  "threads" in your following codes are the same as "numjobs" parameter in fio. Correct? 

 testname = "Sustained Multi-Threaded Random Read Tests by Block Size" 
 seqrand = "Rand" 
 wmix = 0 
 threads = 16 
 runtime = shorttime 
 iops_log = False 
 iodepth = 16 
 AddTestBSShmoo()

**Comment by qiuxin** [comment]
There is a parameter called "--numjobs=$numjobs" in fio. As far as my understanding, "threads" in your following codes are the same as "numjobs" parameter in fio. Correct?

testname = "Sustained Multi-Threaded Random Read Tests by Block Size"
seqrand = "Rand"
wmix = 0
threads = 16
runtime = shorttime
iops_log = False
iodepth = 16
AddTestBSShmoo()

**Comment by earlephilhower** [comment]
Yes.  Each thread itself may have >1 QD.  For the reported test #s on the graph, though, "threads" really means "total outstanding IOs."
