### ISSUE TITLE
ezfio with Windows 2019 and SMB share

### ISSUE THREAD

**Issue by ipvirg** [earlephilhower/ezfio#48]
Hi, 

Trying to run benchmark test against an SMB share mounted on Windows 2019 server. Does that scenario works with ezfio?

Thanks,
Virgil

**Comment by ipvirg** [comment]
ezfio.ps1 powershell script is failing even after setting execution policy in Windows 2019

Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the
about_Execution_Policies help topic at https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y

.\ezfio.ps1
.\ezfio.ps1 cannot be loaded. The file
C:\Users\ezfiouser\ezfio-master\ezfio.ps1 is not digitally signed. You cannot run this script on the current system. For more information about
running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\ezfio.ps1
+ ~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by earlephilhower** [comment]
Looks like you've got quite a locked down system.  There's another ExecutionPolicy you need to set.

Inside a PowerShell window that you're going to run the script from, just do 
````
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
````
and it should disable the signing requirement, just for that PowerShell window and let you continue.

As for working on SMB, no it won't generally.  This test is for running on base disks.  So, I suppose if you set up a VHD from a network share as a local drive it would work, but you can't run it on, say `\\fserver\share1` as that's a filesystem and not a raw disk.

**Comment by ipvirg** [comment]
thanks @earlephilhower
