### ISSUE TITLE
__fio_lock_file: Assertion `!trylock' failed.

### ISSUE THREAD

**Issue by guoweifeng216** [earlephilhower/ezfio#58]
[root@localhost ezfio]# ./ezfio.py -d /dev/nvme0n1 -u 1 --yes
***************************************************************************************************
ezFio test parameters:

               Drive: /dev/nvme0n1
               Model: STORESWIFT SSD2021
              Serial: APOLLO768540
       AvailCapacity: 2673 GiB
      TestedCapacity: 26 GiB
        TestedOffset: 0 GiB
                 CPU: Intel Core i5-9400 CPU @ 2.90GHz
               Cores: 6
           Frequency: 2871
         FIO Version: fio-3.7

Test Description                                                        BW(MB/s)      IOPS  Lat(us)
----------------------------------------------------------------------- -------- --------- --------

---Sequential Preconditioning---                                                                   
Sequential Preconditioning Pass 1                                           DONE      DONE     DONE
Sequential Preconditioning Pass 2                                           DONE      DONE     DONE

---Sustained Multi-Threaded Sequential Read Tests by Block Size---                                 
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=512        0.00         0      0.0
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=1024       0.00         0      0.0
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=2048       0.00         0      0.0
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=4096     743.83   190,421   1344.1
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=8192   2,904.20   371,738    688.4
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=16384  4,490.70   287,405    890.4
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=32768  5,719.53   183,025   1398.4
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=65536  5,719.20    91,507   2797.3
Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=131072 5,712.87    45,703   5601.0

---Sustained Multi-Threaded Random Read Tests by Block Size---                                     
Sustained Multi-Threaded Random Read Tests by Block Size, BS=512            0.00         0      0.0
Sustained Multi-Threaded Random Read Tests by Block Size, BS=1024           0.00         0      0.0
Sustained Multi-Threaded Random Read Tests by Block Size, BS=2048           0.00         0      0.0
Sustained Multi-Threaded Random Read Tests by Block Size, BS=4096       3,856.63   987,297    258.7
Sustained Multi-Threaded Random Read Tests by Block Size, BS=8192       4,606.87   589,680    433.6
Sustained Multi-Threaded Random Read Tests by Block Size, BS=16384      5,340.78   341,810    748.3
Sustained Multi-Threaded Random Read Tests by Block Size, BS=32768      5,589.60   178,867   1430.7
Sustained Multi-Threaded Random Read Tests by Block Size, BS=65536      5,545.69    88,731   2884.6
Sustained Multi-Threaded Random Read Tests by Block Size, BS=131072     5,245.94    41,967   6099.4

---Sequential Write Tests with Queue Depth=1 by Block Size---                                      
Sequential Write Tests with Queue Depth=1 by Block Size, BS=512             0.00         0      0.0
Sequential Write Tests with Queue Depth=1 by Block Size, BS=1024            0.00         0      0.0
Sequential Write Tests with Queue Depth=1 by Block Size, BS=2048            0.00         0      0.0
Sequential Write Tests with Queue Depth=1 by Block Size, BS=4096          491.34   125,784      7.6
Sequential Write Tests with Queue Depth=1 by Block Size, BS=8192          866.33   110,890      8.7
Sequential Write Tests with Queue Depth=1 by Block Size, BS=16384       1,322.93    84,668     11.4
Sequential Write Tests with Queue Depth=1 by Block Size, BS=32768       1,752.69    56,086     17.3
Sequential Write Tests with Queue Depth=1 by Block Size, BS=65536       2,015.75    32,252     30.2
Sequential Write Tests with Queue Depth=1 by Block Size, BS=131072      2,191.73    17,534     55.9

---Random Preconditioning---                                                                       
Random Preconditioning                                                      DONE      DONE     DONE
Random Preconditioning                                                      DONE      DONE     DONE

---Sustained 4KB Random Read Tests by Number of Threads---                                         
Sustained 4KB Random Read Tests by Number of Threads, Threads=1            44.62    11,422     86.0
Sustained 4KB Random Read Tests by Number of Threads, Threads=2            88.15    22,566     87.0
Sustained 4KB Random Read Tests by Number of Threads, Threads=4           174.25    44,609     88.0
Sustained 4KB Random Read Tests by Number of Threads, Threads=8           399.61   102,301     77.6
Sustained 4KB Random Read Tests by Number of Threads, Threads=16          793.57   203,155     78.4
Sustained 4KB Random Read Tests by Number of Threads, Threads=32        1,425.48   364,922     87.1
Sustained 4KB Random Read Tests by Number of Threads, Threads=64        2,392.79   612,554    104.0
Sustained 4KB Random Read Tests by Number of Threads, Threads=128       3,387.25   867,137    147.0
Sustained 4KB Random Read Tests by Number of Threads, Threads=256       3,656.47   936,056    272.9

---Sustained 4KB Random mixed 30% Write Tests by Threads---                                        
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=1           58.12    14,879     85.6
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=2          113.17    28,971     87.8
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=4          214.96    55,029     92.5
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=8          475.34   121,688     89.6
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=16         808.11   206,876    106.3
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=32       1,274.10   326,169    135.6
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=64       1,877.73   480,699    183.5
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=128      2,582.30   661,068    270.3
Sustained 4KB Random mixed 30% Write Tests by Threads, Threads=256      3,440.67   880,811    401.3

---Sustained Perf Stability Test - 4KB Random 30% Write---                                         
Sustained Perf Stability Test - 4KB Random 30% Write                     Runtime  00:20:59      ...
FIO Error!
fio /tmp/tmp_sbpfjk0 --output-format=json+
STDOUT:

STDERR:
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.

Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./ezfio.py", line 1129, in JobWrapper
    val = o['cmdline'](o)
  File "./ezfio.py", line 983, in <lambda>
    o['runtime'])})
  File "./ezfio.py", line 871, in RunTest
    raise FIOError(" ".join(cmdline), code, err, out)
FIOError

Sustained Perf Stability Test - 4KB Random 30% Write                       ERROR     ERROR    ERROR
ERROR DETECTED, ABORTING TEST RUN.

**Comment by earlephilhower** [comment]
Dup of #40.  Use a recent release of FIO to fix the error.
