### ISSUE TITLE
Error out when /proc/sys/fs/aio-nr exceeds /proc/sys/fs/aio-max-nr

### ISSUE THREAD

**Issue by narasimhan-v** [earlephilhower/ezfio#6]
Hi Earle,

Currently, if `/proc/sys/fs/aio-nr` exeeds `/proc/sys/fs/aio-max-nr`, the script exits with fio error.
```
STDOUT:
time     3851  cycles_start=2971940857908
fio: pid=4077, err=11/file:engines/libaio.c:354, func=io_queue_init, error=Resource temporarily unavailable
fio: pid=4095, err=11/file:engines/libaio.c:354, func=io_queue_init, error=Resource temporarily unavailable
3;fio-2.13-28-g059b6;test;0;11;348512528;2904150;726037;120005;2;13707;13.613997;11.054928;1;24050;330.168617;161.437366;1.000000%=151;5.000000%=177;10.000000%=193;20.000000%=217;30.000000%=239;40.000000%=262;50.000000%=286;60.000000%=318;70.000000%=354;80.000000%=414;90.000000%=516;95.000000%=628;99.000000%=956;99.500000%=1112;99.900000%=1480;99.950000%=1640;99.990000%=2064;0%=0;0%=0;0%=0;39;24062;344.682689;161.719782;7363;12980;0.390511%;11341.037492;568.079527;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;2.382052%;7.343719%;87131642;0;8660;100.0%;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;0.01%;0.01%;0.01%;0.01%;0.01%;0.01%;35.12%;53.81%;8.38%;1.88%;0.79%;0.01%;0.01%;0.01%;0.01%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;nvme0n1;86976293;0;0;0;28073776;0;32065504;100.00%

STDERR:
fio: check /proc/sys/fs/aio-max-nr
fio: check /proc/sys/fs/aio-max-nr

Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./ezfio.py", line 632, in JobWrapper
    val = o['cmdline'](o)
  File "./ezfio.py", line 491, in <lambda>
    o['runtime'])})
  File "./ezfio.py", line 427, in RunTest
    raise FIOError(" ".join(cmdline), code, err, out)
FIOError

Sustained 4KB Random Read Tests by Number of Threads, Threads=256          ERROR     ERROR    ERROR
ERROR DETECTED, ABORTING TEST RUN.

```

Is this something we can skip values ?
Can this be notified to user (ex: with 0s) and proceeded to other runs ?
If yes, can we follow the same approach for all such instances ?

**Comment by earlephilhower** [comment]
Many tests are at 256 QD, so this would skip a lot of stuff.

This kernel value can be increased with a sysctl, so that would be the better option, no?  Another simple check in the main routine followed by instructions on how to increase it and an abort would be best I think.  Oracle even recommends it for their databases under Linux, so it should "just work."

Can you try running:
    sudo sysctl -w fs.aio-max-nr=1048576
and then re-running the tests?  If so, I'll throw together a patch that checks and shows how to set it from the command line or sysctl.conf.

**Comment by earlephilhower** [comment]
Also, if you skip these tests at high QD you'll actually end up skipping the random preconditioning steps which would basically invalidate all results.

I've pushed a commit that checks the kernel value and suggests a way of fixing it if it is too low before beginning the test.  Can you give that a try?

**Comment by narasimhan-v** [comment]
Thanks @earlephilhower , will check it, and report.
And I agree that it is upto user to have a suitable aio-max-nr value.

**Comment by narasimhan-v** [comment]
@earlephilhower Works fine. Thanks.
Closing the issue
